version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: usermanager
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL_POSTGRESQL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      API_SECURITY_TOKEN: ${API_SECURITY_TOKEN}
    ports:
      - "8080:8080"
volumes:
  db_data: